# Generated by Django 4.2.7 on 2023-11-15 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='berita',
            name='fotopenulis',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
