# Generated by Django 4.2.7 on 2023-11-17 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('News', '0004_alter_berita_kategoriid'),
    ]

    operations = [
        migrations.CreateModel(
            name='beritaupdate1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('isi', models.CharField(max_length=9999)),
                ('kategoriID', models.IntegerField()),
                ('gambar', models.ImageField(upload_to='media')),
                ('penulis', models.CharField(max_length=255)),
                ('fotopenulis', models.ImageField(null=True, upload_to='media')),
                ('status', models.CharField(choices=[('publish', 'publish'), ('draft', 'draft')], max_length=200)),
                ('publikasi', models.CharField(max_length=255)),
                ('deskripsi', models.CharField(max_length=255)),
                ('kategori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='News.kategori')),
            ],
        ),
    ]
